[book]
title = "Asynchronous Programming in Rust（中文翻译）"
authors = ["Taylor Cramer", "Nicholas Cameron", "Open source contributors"]

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/scheshan/async-book-cn"
site-url = "/async-book/"

[output.linkcheck2]
follow-web-links = true
traverse-parent-directories = false
exclude = [ 'blog\.cloudflare\.com' ]
